### ISSUE TITLE
Xcode 6.1.1 下无法运行

### ISSUE THREAD

**Issue by dandyweng** [jxd001/Swift-ZhihuDaily#11]
在 Xcode 6.1.1 下完全运行不了，报了一大堆错误，小白表示完全不知道该怎么修复。解决一下吧，做事情不要虎头蛇尾嘛。
![screen shot 2015-02-23 at 22 57 41](https://cloud.githubusercontent.com/assets/5425979/6329946/685678ae-bbaf-11e4-9194-d29b556963ef.png)

**Comment by jxd001** [comment]
不好意思，工作太忙，已修复。
